name: base_starter
description: >
  Highly scalable Flutter starter kit, designed with an optimal predefined structure 
  and inclusive of libraries that are widely applicable in numerous use cases.
publish_to: "none"
version: 0.0.1+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter
  collection: any
  async: any
  meta: any
  intl: any
  js: any
  flutter_localizations:
    sdk: flutter

  # Stream
  stream_transform: ^2.1.0
  rxdart: ^0.27.7

  # BLoC
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4
  bloc_concurrency: ^0.2.5

  # Codegen
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.1

  # Networking
  dio: ^5.4.3+1

  # Persisting
  shared_preferences: ^2.2.3
  drift: ^2.18.0
  sqlite3_flutter_libs: ^0.5.21

  # Logging
  talker_flutter: ^4.2.0
  talker_dio_logger: ^4.2.0
  talker_bloc_logger: ^4.2.0
  talker_riverpod_logger: ^1.0.0

  # Utils
  pure: ^0.2.0
  platform_info: ^4.0.2
  path: ^1.9.0
  path_provider: ^2.1.3
  mocktail: ^1.0.3
  equatable: ^2.0.5
  share_plus: ^9.0.0
  package_info_plus: ^8.0.0
  device_info_plus: ^10.1.0

  # UI
  gap: ^3.0.1
  group_button: ^5.3.4
  flutter_easyloading: ^3.0.5
  auto_size_text: ^3.0.0
  fluttertoast: ^8.2.5
  ispect: ^1.1.3

  # Others
  provider: ^6.1.2
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  go_router: ^14.1.0
  flutter_secure_storage: ^9.1.1
  envied: ^0.5.4+1
  
dev_dependencies:
  # Testing
  flutter_test:
    sdk: flutter

  # Lints
  sizzle_lints: ^2.0.2

  # Utils
  flutter_gen_runner: ^5.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

  # Codegen
  json_serializable: ^6.8.0
  drift_dev: ^2.18.0
  build_runner: ^2.4.9
  freezed: ^2.5.2
  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  envied_generator: ^0.5.4+1

flutter:
  uses-material-design: true

  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - .env

flutter_gen:
  output: lib/src/core/assets/generated
  line_length: 80

flutter_intl:
  enabled: true
  class_name: GeneratedLocalization
  main_locale: en
  arb_dir: lib/src/core/localization/translations
  output_dir: lib/src/core/localization/generated

flutter_launcher_icons: # dart pub run flutter_launcher_icons
  #  image_path: "assets/images/icon-128x128.png"
  image_path_android: "assets/images/icon-1024x1024.png"
  image_path_ios: "assets/images/icon-1024x1024.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  # adaptive_icon_background: "assets/images/christmas-background.png" # only available for Android 8.0 devices and above
  # adaptive_icon_foreground: "assets/images/icon-foreground-432x432.png" # only available for Android 8.0 devices and above
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true

  # web:
  #   generate: true
  #   image_path: "assets/images/icon-1024x1024.png"
  #   # background_color: "#hexcode"
  #   # theme_color: "#hexcode"

  # windows:
  #   generate: true
  #   image_path: "assets/images/icon-1024x1024.png"
  #   icon_size: 48 # min:48, max:256, default: 48

  # macos:
  #   generate: true
  #   image_path: "assets/images/icon-1024x1024.png"
